#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    platform: $PLATFORM
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=genesis.block
      - ORDERER_GENERAL_LOCALMSPID=TradeOrdererOrgMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/trade.com/orderers/orderer.trade.com/msp:/etc/hyperledger/msp
      - ./channel-artifacts/genesis.block:/etc/hyperledger/fabric/genesis.block
    ports:
      - 7050:7050

  peer:
    container_name: peer
    image: hyperledger/fabric-peer:$IMAGE_TAG
    platform: $PLATFORM
    environment:
      - CORE_PEER_ID=peer0.devorg.trade.com
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer:7051
      - CORE_PEER_LOCALMSPID=DevOrgMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ./crypto-config/peerOrganizations/devorg.trade.com/peers/peer0.devorg.trade.com/msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev
    ports:
      - 7051:7051
    depends_on:
      - orderer

  ca:
    container_name: ca
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    platform: $PLATFORM
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    volumes:
      - ./crypto-config/peerOrganizations/devorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.devorg.trade.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    ports:
      - "7054:7054"

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    platform: $PLATFORM
    tty: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DevOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c '/opt/trade/setupChannel.sh'
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ./crypto-config/peerOrganizations/devorg.trade.com/users/Admin@devorg.trade.com/msp:/etc/hyperledger/msp
        - ./channel-artifacts:/opt/trade/channel-artifacts
        - ./../../chaincode:/opt/gopath/src/chaincodedev/chaincode
        - ./:/opt/trade
    depends_on:
      - orderer
      - peer

  chaincode-java:
    container_name: chaincode-java
    image: hyperledger/fabric-javaenv:$IMAGE_TAG
    platform: $PLATFORM
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=peer0.devorg.trade.com
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DevOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/chaincode
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ./crypto-config/peerOrganizations/devorg.trade.com/peers/peer0.devorg.trade.com/msp:/etc/hyperledger/msp
        - ./../../contracts/v1/letterOfCredit:/opt/gopath/src/chaincode/letterOfCredit
    depends_on:
      - orderer
      - peer

  chaincode-node:
    container_name: chaincode-node
    image: hyperledger/fabric-nodeenv:$IMAGE_TAG
    platform: $PLATFORM
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=peer0.devorg.trade.com
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DevOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    working_dir: /opt/gopath/src/chaincode
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ./crypto-config/peerOrganizations/devorg.trade.com/peers/peer0.devorg.trade.com/msp:/etc/hyperledger/msp
        - ./../../contracts/v1/trade:/opt/gopath/src/chaincode/trade
    depends_on:
      - orderer
      - peer
